### ISSUE TITLE
'期现套利策略表' 是人工手动输入吗？

### ISSUE THREAD

**Issue by xiandong79** [matrix-tang/Futures-Spot-Arbitrage-Binance-V1#2]
问题1: '期现套利策略表' 是人工手动输入吗？

```
        Box::pin(service::spot_all_ticker(price_tx.clone())),
        Box::pin(service::futures_all_ticker(price_tx.clone())),
        Box::pin(service::delivery_all_ticker(price_tx.clone())),
```
这里监控了 所有 binance symbols 的 websocket 的 Individual Symbol Mini Ticker Stream 作为价格输入

问题2：

option_amount 是一个order size，还是 max position。应该有一个 持仓上限。 还是说 order size = max position, 最多只持有1个 order size？

**Comment by matrix-tang** [comment]
1、策略表，需要自己手动输入，设置好
2、option_amount, 现货、U本位期货代表币数量，币本位期货代表的开仓的合约张数，不是max position

**Comment by xiandong79** [comment]
问题2 延续：

那么是一单 成交全部的 仓位，即 option_amount 吗，即 不需要拆单？

一般来说又会有个 max_position = 50万 doge，  option_amount = per_order_size = 1万 doge @matrix-tang

**Comment by matrix-tang** [comment]
这里边没有设置max_position概念，你每条策略就是单独的套利多少币，如果担心滑点，可以在策略表插入多条同一币种策略

总仓位等于 你同一币种策略例如：BTCUSDT - BTCUSD_240927，多条同一个策略的总和
